app = "kimibot"
primary_region = "nrt"  # Tokyo region
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"
  FLASK_ENV = "production"
  # 添加其他必要環境變數，但隱藏實際值，通過flyctl secrets設置
  LOG_LEVEL = "debug"
  DATABASE_PATH = "/app/database/linebot.db"
  WEBHOOK_URL = "https://kimibot.fly.dev/api/webhook"
  # LINE_CHANNEL_SECRET 和 LINE_CHANNEL_ACCESS_TOKEN 應通過 flyctl secrets 設置

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# 添加進程保持配置，防止應用自動關閉
[processes]
  # 直接使用Python運行webapp，避免Gunicorn啟動問題
  app = "/app/start.sh"
  # 添加保持系統運行的後台進程
  cron = "python -m scheduler.reminder_scheduler"

[mounts]
  source = "line_bot_data"
  destination = "/app/database"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 