app = "line-finance-assistant"
primary_region = "nrt"  # Tokyo region
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "line_bot_data"
  destination = "/app/database"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false 